# Generated by Django 5.2.9 on 2025-12-09 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailychallenge'),
        ('game', '0006_challenge_share_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.dailychallenge')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['daily_challenge', 'user'], name='accounts_da_daily_c_b1f8ac_idx')],
                'unique_together': {('daily_challenge', 'user')},
            },
        ),
    ]
