# Generated by Django 5.2.9 on 2025-12-10 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings'),
        ('game', '0007_gamesession_game_gamese_challen_66da73_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='allowed_sender_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ChallengeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='game.challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='accounts_ch_recipie_ff8d98_idx'), models.Index(fields=['challenge', 'recipient'], name='accounts_ch_challen_295993_idx')],
            },
        ),
    ]
