# Generated by Django 5.2.9 on 2025-12-10 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_worddefinitioncache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
