# Generated by Django 5.2.9 on 2025-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
    ]
