# Generated by Django 5.2.9 on 2025-12-09 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_challenge_recipients_challenge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('challenge', 'Challenge'), ('practice', 'Practice')], default='challenge', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('submissions', models.JSONField(blank=True, default=list)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.challenge')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['challenge'], name='game_gamese_challen_8a3192_idx'), models.Index(fields=['player_user_id'], name='game_gamese_player__4284d6_idx')],
            },
        ),
    ]
