# Generated by Django 5.2.9 on 2025-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='hint_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
