# Generated by Django 5.2.9 on 2025-12-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_hint_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='shuffle_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
