# Generated by Django 5.2.9 on 2025-12-09 14:25

from django.db import migrations, models
import game.slug_utils


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_shuffle_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='share_slug',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
