# Generated by Django 5.2.9 on 2025-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_challenge_share_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['challenge', '-score', 'end_time'], name='game_gamese_challen_66da73_idx'),
        ),
    ]
