# Generated by Django 5.2.9 on 2025-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamesession_game_gamese_challen_66da73_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
