# Generated by Django 5.2.9 on 2025-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_challenge_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=5),
        ),
    ]
